language: node_js
node_js:
  - "10.15.0"

script:
  - npm i
  - sed -i 's/if(log.blockNumber !== null)/if(typeof log !== "object")return log;if(log.blockNumber !== null)/g' node_modules/web3/lib/web3/formatters.js
  - npm run build
  - echo 'buidl.secondstate.io' > ./dist/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master